import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import Notification from "./components/Notification";
import AuthSession from "./components/AuthSession";
import { AppWrapper } from "./context";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// REDE

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthSession>
      <html lang="es">
        <body className={inter.className} style={{ scrollBehavior: "smooth" }}>
          <AppWrapper>
            <Navbar />
            {children}
            <Notification />
          </AppWrapper>
        </body>
      </html>
    </AuthSession>
  );
}
